package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] EBCDIC_ENCODING = "cp1047".toCharArray();
public static final char[] FORMAT1016334848 = "----".toCharArray();
public static final char[] LITERAL_TRDPBEXC = "TRDPBEXC".toCharArray();
 
}
