package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
public class SQLS {
 
public static final char[] SQL_150892171 = "INSERT INTO TBTRDEXC ( EXC_TYPE , EXC_DESCRIPTION ) VALUES ( ? , ? )".toCharArray() ;
public static final char[] SQL_150892171_1 = "INSERT INTO TBTRDEXC ( EXC_TYPE , EXC_DESCRIPTION ) VALUES ( ? , ? )".toCharArray() ;
public static final char[] SQL_150892171_2 = "INSERT INTO TBTRDEXC ( EXC_TYPE , EXC_DESCRIPTION ) VALUES ( ? , ? )".toCharArray() ;
 
}
