package com.optum.uhg.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.utility.CFUtil;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] SPACE_50 = CFUtil.fillSpaces(50);
public static final char[] EBCDIC_ENCODING = "cp1047".toCharArray();
public static final char[] FORMAT1016334848 = "----".toCharArray();
public static final char[] FORMAT2062691925 = "ZZZZZZZZ9".toCharArray();
public static final char[] LITERAL_1118165632 = "**************************************************".toCharArray();
public static final char[] LITERAL_1781749721 = "Security lookup failed : sqlcode = ".toCharArray();
public static final char[] LITERAL_872240021 = "Security Not found !!                             ".toCharArray();
public static final char[] LITERAL_CF03SECU = "CF03SECU".toCharArray();
public static final char[] LITERAL_SIZE = "SIZE".toCharArray();
 
}
