package com.optum.uhg.app.common;
/* Java Code Generated by CloudFrame */ 
public class SQLS {
 
public static final char[] SQL_729692624 = "SELECT SEDOL , RIC , INTLKEY , COMPANY , COUNTRY , INDUSTRY , SECTOR , FFMCAPMILUSD , SECTORWEIGHT FROM TBDEMSEC WHERE ISIN = ?".toCharArray() ;
 
}
