package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.data.Field;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] FORMAT1016334848 = "----".toCharArray();
public static final char[] FORMAT_34170218 = "ZZZ".toCharArray();
public static final char[] FORMAT_491838655 = "-,---,---.00".toCharArray();
public static final char[] LITERAL_00 = "00".toCharArray();
public static final char[] LITERAL_Accepted_B12_ = "Accepted            ".toCharArray();
public static final char[] LITERAL_B = "B".toCharArray();
public static final char[] LITERAL_Matched_B13_ = "Matched             ".toCharArray();
public static final char[] LITERAL_Overdue_MN_Buyer_B2_Invld = "Overdue-Buyer Invld ".toCharArray();
public static final char[] LITERAL_Overdue_MN_Buyer_B3_Acct = "Overdue-Buyer Acct  ".toCharArray();
public static final char[] LITERAL_Overdue_MN_MissingOrdr_B_ = "Overdue-MissingOrdr ".toCharArray();
public static final char[] LITERAL_Overdue_MN_OrderStatus_B_ = "Overdue-OrderStatus ".toCharArray();
public static final char[] LITERAL_Overdue_MN_Rejected_B4_ = "Overdue-Rejected    ".toCharArray();
public static final char[] LITERAL_Overdue_MN_Security_B4_ = "Overdue-Security    ".toCharArray();
public static final char[] LITERAL_Overdue_MN_SellerInvld_B_ = "Overdue-SellerInvld ".toCharArray();
public static final char[] LITERAL_Overdue_MN_Seller_B2_Acct = "Overdue-Seller Acct ".toCharArray();
public static final char[] LITERAL_Settled_B13_ = "Settled             ".toCharArray();
public static final char[] LITERAL_TRDPB006 = "TRDPB006".toCharArray();
public static final char[] LITERAL_Unknown_B13_ = "Unknown             ".toCharArray();
public static final char[] LOW_VALUE_215749166 = Field.fillLowValue(160);
public static final char[] MODE_WRITE_ONLY_36397 = "w".toCharArray();
 
}
