package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.data.Field;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] EBCDIC_ENCODING = "cp1047".toCharArray();
public static final char[] FORMAT1016334848 = "----".toCharArray();
public static final char[] FORMAT_34170218 = "ZZZ".toCharArray();
public static final char[] FORMAT_491838655 = "-,---,---.00".toCharArray();
public static final char[] HEX_1 = Field.getString(new byte[] {(byte)0xD6,(byte)0xA5,(byte)0x85,(byte)0x99,(byte)0x84,(byte)0xA4,(byte)0x85,(byte)0x60,(byte)0xC2,(byte)0xA4,(byte)0xA8,(byte)0x85,(byte)0x99,(byte)0x40,(byte)0xC9,(byte)0x95,(byte)0xA5,(byte)0x93,(byte)0x84}).toCharArray();
public static final char[] HEX_2 = Field.getString(new byte[] {(byte)0xD6,(byte)0xA5,(byte)0x85,(byte)0x99,(byte)0x84,(byte)0xA4,(byte)0x85,(byte)0x60,(byte)0xE2,(byte)0x85,(byte)0x93,(byte)0x93,(byte)0x85,(byte)0x99,(byte)0xC9,(byte)0x95,(byte)0xA5,(byte)0x93,(byte)0x84}).toCharArray();
public static final char[] HEX_3 = Field.getString(new byte[] {(byte)0xD6,(byte)0xA5,(byte)0x85,(byte)0x99,(byte)0x84,(byte)0xA4,(byte)0x85,(byte)0x60,(byte)0xE2,(byte)0x85,(byte)0x83,(byte)0xA4,(byte)0x99,(byte)0x89,(byte)0xA3,(byte)0xA8}).toCharArray();
public static final char[] HEX_4 = Field.getString(new byte[] {(byte)0xD6,(byte)0xA5,(byte)0x85,(byte)0x99,(byte)0x84,(byte)0xA4,(byte)0x85,(byte)0x60,(byte)0xC2,(byte)0xA4,(byte)0xA8,(byte)0x85,(byte)0x99,(byte)0x40,(byte)0xC1,(byte)0x83,(byte)0x83,(byte)0xA3}).toCharArray();
public static final char[] HEX_5 = Field.getString(new byte[] {(byte)0xD6,(byte)0xA5,(byte)0x85,(byte)0x99,(byte)0x84,(byte)0xA4,(byte)0x85,(byte)0x60,(byte)0xE2,(byte)0x85,(byte)0x93,(byte)0x93,(byte)0x85,(byte)0x99,(byte)0x40,(byte)0xC1,(byte)0x83,(byte)0x83,(byte)0xA3}).toCharArray();
public static final char[] HEX_6 = Field.getString(new byte[] {(byte)0xD6,(byte)0xA5,(byte)0x85,(byte)0x99,(byte)0x84,(byte)0xA4,(byte)0x85,(byte)0x60,(byte)0xD6,(byte)0x99,(byte)0x84,(byte)0x85,(byte)0x99,(byte)0xE2,(byte)0xA3,(byte)0x81,(byte)0xA3,(byte)0xA4,(byte)0xA2}).toCharArray();
public static final char[] HEX_7 = Field.getString(new byte[] {(byte)0xD6,(byte)0xA5,(byte)0x85,(byte)0x99,(byte)0x84,(byte)0xA4,(byte)0x85,(byte)0x60,(byte)0xD4,(byte)0x89,(byte)0xA2,(byte)0xA2,(byte)0x89,(byte)0x95,(byte)0x87,(byte)0xD6,(byte)0x99,(byte)0x84,(byte)0x99}).toCharArray();
public static final char[] HEX_8 = Field.getString(new byte[] {(byte)0xD6,(byte)0xA5,(byte)0x85,(byte)0x99,(byte)0x84,(byte)0xA4,(byte)0x85,(byte)0x60,(byte)0xD9,(byte)0x85,(byte)0x91,(byte)0x85,(byte)0x83,(byte)0xA3,(byte)0x85,(byte)0x84}).toCharArray();
public static final char[] LITERAL_00 = "00".toCharArray();
public static final char[] LITERAL_Accepted_B12_ = "Accepted            ".toCharArray();
public static final char[] LITERAL_B = "B".toCharArray();
public static final char[] LITERAL_Matched_B13_ = "Matched             ".toCharArray();
public static final char[] LITERAL_Settled_B13_ = "Settled             ".toCharArray();
public static final char[] LITERAL_TRDPB006 = "TRDPB006".toCharArray();
public static final char[] LITERAL_Unknown_B13_ = "Unknown             ".toCharArray();
public static final char[] LOW_VALUE_215749166 = Field.fillLowValue(160);
public static final char[] MODE_WRITE_ONLY_36397 = "w".toCharArray();
 
}
