package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
public class SQLS {
 
public static final char[] SQL_150892171 = "INSERT INTO TBTRDEXC ( EXC_TYPE , EXC_DESCRIPTION ) VALUES ( ? , ? )".toCharArray() ;
public static final char[] SQL_150892171_1 = "INSERT INTO TBTRDEXC ( EXC_TYPE , EXC_DESCRIPTION ) VALUES ( ? , ? )".toCharArray() ;
public static final char[] SQL_150892171_2 = "INSERT INTO TBTRDEXC ( EXC_TYPE , EXC_DESCRIPTION ) VALUES ( ? , ? )".toCharArray() ;
public static final char[] SQL_1886454020 = "UPDATE TBTRDMAC SET MAC_BALANCE = ? WHERE MAC_CURRENCY = ? AND MAC_NUMBER = ?".toCharArray() ;
public static final char[] SQL_2131911232 = "SELECT MAC_BALANCE FROM TBTRDMAC WHERE MAC_CURRENCY = ? AND MAC_NUMBER = ? FOR UPDATE OF MAC_BALANCE".toCharArray() ;
 
}
