package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.utility.CFUtil;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] SPACE_200 = CFUtil.fillSpaces(200);
public static final char[] EBCDIC_ENCODING = "cp1047".toCharArray();
public static final char[] FORMAT1016334848 = "----".toCharArray();
public static final char[] LITERAL_1086420419 = CFUtil.pad(200, "Customer is Inactive", " ",CFUtil.RIGHT_PAD);
public static final char[] LITERAL_1349680305 = "Customer Access failed. SQLCODE = ".toCharArray();
public static final char[] LITERAL_1395303119 = CFUtil.pad(200, "Customer Not Found", " ",CFUtil.RIGHT_PAD);
public static final char[] LITERAL_A = "A".toCharArray();
public static final char[] LITERAL_MSTPB001 = "MSTPB001".toCharArray();
public static final char[] LITERAL_SIZE = "SIZE".toCharArray();
 
}
