package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.utility.CFUtil;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] SPACE_200 = CFUtil.fillSpaces(200);
public static final char[] EBCDIC_ENCODING = "cp1047".toCharArray();
public static final char[] FORMAT1016334848 = "----".toCharArray();
public static final char[] LITERAL_1961717773 = CFUtil.pad(200, "SECURITY Not Found", " ",CFUtil.RIGHT_PAD);
public static final char[] LITERAL_679803187 = "SECURITY Access failed. SQLCODE = ".toCharArray();
public static final char[] LITERAL_MSTPB002 = "MSTPB002".toCharArray();
public static final char[] LITERAL_SIZE = "SIZE".toCharArray();
 
}
