package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
public class SQLS {
 
public static final char[] SQL_978740778 = "SELECT SEC_CURRENCY , SEC_DESCRIPTION , SEC_SYMBOL , SEC_SHARE_CLASS_FIGI , SEC_TYPE FROM TBTRDSEC WHERE SEC_FIGI = ?".toCharArray() ;
 
}
